services:
  agente-bbdd:
    build: .
    container_name: agente-bbdd
    stdin_open: true 
    tty: true
    volumes:
      - ./queries:/app/queries
    env_file:
      - .env
    ports:
      - "8501:8501"